# Generated by Django 4.2.1 on 2023-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
